# Change the default Omarchy look'n'feel

# https://wiki.hypr.land/Configuring/Basics/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 1
    gaps_out = 0
    # border_size = 0

    # Layout: dwindle (default), master, or scrolling
    layout = dwindle
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 12
    rounding_power = 1.8

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    dim_inactive = true
    dim_strength = 0.10

    blur {
        enabled = true
        size = 6
        passes = 3
        special = true
        brightness = 0.60
        contrast = 0.75
    }
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#animations
animations {
    # Disable all animations
    # enabled = no
    workspace_wraparound = true
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

env = XCURSOR_THEME,macOS
env = XCURSOR_SIZE,60
env = HYPRCURSOR_THEME,macOS
env = HYPRCURSOR_SIZE,60
